version: "3.8"

services:
  nestjs_app:
    image: node:22
    ports:
      - "${HOST_HTTP_PORT}:3000"
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - ""
    command: "npm run start:dev"
    depends_on:
      - db

  db:
      image: postgres:alpine
      ports:
          - ${DB_PORT}:5432
      environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
          - db_data:/var/lib/postgresql/data:rw

volumes:
    db_data:
